SAMPWIDTH = 2

NCHANNELS_IN = 2
FRAME_SIZE_IN = NCHANNELS_IN * SAMPWIDTH

NCHANNELS_OUT = 1
FRAME_SIZE_OUT = NCHANNELS_OUT * SAMPWIDTH

FRAMERATE = 48000
DEFAULT_FADE_TIME = 3

DEFAULT_ROTATION_SPEED = 1
